service:
  name: mails-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    EMAILS_TABLE_NAME: ${self:custom.EmailsTable.name}
  iamRoleStatements:
    - ${file(iam/EmailsTableIAM.yml):EmailsTableIAM}

resources:
  Resources:
    EmailsTable: ${file(resources/EmailsTable.yml):EmailsTable}

functions:
  createNotiEmail:
    handler: src/handlers/createNotiEmail.handler
    events:
      - http:
          method: POST
          path: /mail/

  deleteNotiEmail:
    handler: src/handlers/deleteNotiEmailById.handler
    events:
      - http:
          method: DELETE
          path: /mail/delete/{id}


  changeNotiEmail:
    handler: src/handlers/changeNotiEmail.handler
    events:
      - http:
          method: PUT
          path: /mail/change/{id}

  getNotiEmailByUni:
    handler: src/handlers/getNotiEmailByUni.handler
    events:
      - http:
          method: GET
          path: /mail/list/{prefix_uni}


custom:
  EmailsTable:
    name: !Ref EmailsTable
    arn: !GetAtt EmailsTable.Arn
  bundle:
    linting: false